[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.build_meta"

[project]
name = "gsl_detect"
version = "0.0.1"
description = "Greek sign language detection using machine learning"
authors = [
  { name = "Fenia Papadouli", email = "gapapadouli@gmail.com"},
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = "~=3.12.0"
dependencies = [
    "mkdocs",
    "loguru",
    "pip",
    "python-dotenv",
    "torch",
    "ruff",
    "tqdm",
    "typer",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "mediapipe",
    "streamlit"
]

[tool.ruff]
line-length = 99
src = ["gsl_detect"]
include = ["pyproject.toml", "gsl_detect/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["gsl_detect"]
force-sort-within-sections = true

